#!/usr/bin/env bash
# This script transfers a file from our
# client to a server

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    echo -e "Host *\n\tStrictHostKeyChecking no" > sudo ~/.ssh/config
    sudo chmod 400 ~/.ssh/config
    scp -i "$4" "$1" "$3"@"$2":~/
fi
