#!/usr/bin/env bash
# This script transfers a file from our
# client to a server

a=3
if [ "$#" -lt "$a" ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    echo "Host * StrictHostKeyChecking no" > ~/.ssh/config
    chmod 400 ~/.ssh/config
    scp -i "$4" "$1" "$3"@"$2":~/
fi
