#!/usr/bin/env bash
# This script installs and configures nginx
# on a machine when run
sudo apt-get update
sudo apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.html
service nginx restart
