#!/usr/bin/env bash
# This script conntains commands to configure
# an unbuntu machine with a redirection
replace="server_name _;\n\treturn 301 $scheme:https//www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;"

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "s|server_name _;|$replace|" /etc/nginx/sites-available/default
service nginx restart
