#!/usr/bin/env bash
# This script creates a custom 404 page
# with some text

replace="server_name _;\n\terror_page 404 /err_404.html;"

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err_404.html > /dev/null
sudo sed -i "s|server_name _;|$replace|" /etc/nginx/sites-available/default
sudo service nginx restart
