#!/usr/bin/env bash
# This script installs and configures
# HAproxy on the load balancer server

frontend="\nfrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend nginx_webservers\n"
backend="backend nginx_webservers\n\tbalance roundrobin\n\tserver 220236-web-01 10.247.223.115:80 check\n\tserver 2220236-web-02 10.247.144.208:80 check"
sudo apt-get update
sudo apt-get -y install haproxy
echo -e "ENABLED=1" | sudo tee -a /etc/default/haproxy >/dev/null
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo -e "$backend" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
