#!/usr/bin/env bash
# This script installs and configures
# HAproxy on the load balancer server

frontend="\nfrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend nginx_webservers"
backend="\nnginx_webservers\n\tbalance roundrobin\n\t server 220236-web-01  100.26.235.45:80 check\n\tserver 2220236-web-02 100.25.222.11:80 check"
sudo apt-get update
sudo apt-get install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$frontend" >> sudo /etc/haproxy/haproxy.cfg
echo "$backend" >> sudo /etc/haproxy/haproxy.cfg
sudo service haproxy restart
