#!/usr/bin/env bash
# This script creates a backup of all databases

sudo mysqldump -u root --all-databases -p"$1" 2> /dev/null | sudo tee backup.sql > /dev/null
tar -zvcf "$(date +%d-%m-%Y).tar.gz" backup.sql
