#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# if number is multiple of 3, print 'Fizz'
# if number is multiple of 5, print 'Buzz'
# if number is multiple of both 3 and 5, print 'FizzBuzz'

for i in {1..100}
do
  if [[ $((i % 5)) -eq 0 && $((i % 3)) -eq 0 ]]
  then
    echo 'FizzBuzz'
  elif [ $((i % 3)) -eq 0 ]
  then
    echo 'Fizz'
  elif [ $((i % 5)) -eq 0 ]
  then
    echo 'Buzz'
  else
    echo "$i"
  fi
done
