#!/usr/bin/env bash
# This script reads and cuts the /etc/passwd
# file and leaves only the username user id
# and Home directory

file="/etc/passwd"

while read -r line
do
   cut -d ":" -f 1,3,6 "$line"
done <<< $file 
