#!/usr/bin/env bash
# Print "Best School" ten times with while loop
# If 9th iteration, print 'Hi' instead of "Best School"

i=1

while [ $i -le 10 ]
do
 echo 'Best School'
 if [ $i -eq 9 ]
 then
 echo 'Hi'
 fi

 ((i++))
done 
