#!/usr/bin/env bash
# While loop that displays numbers from one to 20
# Display some prompt intead of the numbers in sime cases

i=1

while [ $i -le 20 ]
do
  echo $i

  case $i in
  4 )
    echo 'bad luck from China';;
  9 )
    echo 'bad luck from Japan';;
  17 )
    echo 'bad luck from Italy';;
  esac

  ((i++))
done
