#!/usr/bin/env bash
# This bash script changes your home ip

cp /etc/hosts ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cat ~/hosts.new > /etc/hosts
